export { default } from "./src/wallet-manager-tron.js";
export { default as WalletAccountReadOnlyTron } from "./src/wallet-account-read-only-tron.js";
export { default as WalletAccountTron } from "./src/wallet-account-tron.js";
export type TronTransactionReceipt = import("tronweb").TransactionInfo;
export type TronTransactionDetails = import("./src/wallet-account-read-only-tron.js").TronTransactionDetails;
export type FeeRates = import("@tetherto/wdk-wallet").FeeRates;
export type KeyPair = import("@tetherto/wdk-wallet").KeyPair;
export type TransactionResult = import("@tetherto/wdk-wallet").TransactionResult;
export type TransferOptions = import("@tetherto/wdk-wallet").TransferOptions;
export type TransferResult = import("@tetherto/wdk-wallet").TransferResult;
export type Finality = import("@tetherto/wdk-wallet").Finality;
export type TransactionReceipt = import("@tetherto/wdk-wallet").TransactionReceipt;
export type WaitForTransactionTarget = import("@tetherto/wdk-wallet").WaitForTransactionTarget;
export type WaitForTransactionOptions = import("@tetherto/wdk-wallet").WaitForTransactionOptions;
export type TronTransaction = import("./src/wallet-account-read-only-tron.js").TronTransaction;
export type TronTrxTransfer = import("./src/wallet-account-read-only-tron.js").TronTrxTransfer;
export type TronSmartContractCall = import("./src/wallet-account-read-only-tron.js").TronSmartContractCall;
export type Transaction = import("./src/wallet-account-read-only-tron.js").Transaction;
export type ContractFunctionParameter = import("./src/wallet-account-read-only-tron.js").ContractFunctionParameter;
export type TriggerSmartContractOptions = import("./src/wallet-account-read-only-tron.js").TriggerSmartContractOptions;
export type EstimateEnergyCostValue = import("./src/wallet-account-read-only-tron.js").EstimateEnergyCostValue;
export type TronWalletConfig = import("./src/wallet-account-read-only-tron.js").TronWalletConfig;
export type TronActivationFee = import("./src/wallet-account-read-only-tron.js").TronActivationFee;
export type TronSignedTransaction = import("./src/wallet-account-tron.js").TronSignedTransaction;
